### PR TITLE
Support dragonmantank/cron-expression v3

### PR DESCRIPTION
**Pull request by mareksuscak**
| Q             | A
| ------------- | ---
| Fixed tickets | #...

### CODE REVIEW

**Comment by PabloKowalczyk** [comment]
Hello @mareksuscak, I was thinking about this change earlier but v3 of dragonmantank/cron-expression introduces some behavior change (https://github.com/dragonmantank/cron-expression/blob/master/CHANGELOG.md#300---2020-03-25) in interpretation of "day of month" and "day of week" elements, this is why it must be postponed to v3 release of Crunz.

What is your use case?

**Comment by mareksuscak** [comment]
You're absolutely right. I ran into a couple of roadblocks where a stagnant dependency was blocking other dependency updates that were crucial to me. Not in this case. I just like to keep dependencies up to date on all my projects.

**Comment by PabloKowalczyk** [comment]
OK then, will be happy to merge your PR after `master` became `v3` dev branch, till then you can try to fix issues reported by PHPStan in TravisCI.

**Comment by PabloKowalczyk** [comment]
Fixed by https://github.com/lavary/crunz/pull/356

**Pull request closed without merging**
