### PR TITLE
Symfony 6 Support

### LINKED ISSUE #389: Support for Symfony 6
Symfony 6 was just released, support for it would be great.

I don't see any breaking changes for now, so I hope a simple add to the composer.json should be all it takes, but don't take my word for it :-)

### PR DESCRIPTION
**Pull request by bashgeek**
Fixes #389 

Added Symfony 6 versions to composer.json and fixed some type hints that are now required. All tests run fine after.

### CODE REVIEW

**Comment by PabloKowalczyk** [comment]
Could you add Symfony 6 checks to strategy matrix in `.github/workflows/code_checks.yaml` and change target branch to `3.2` (https://github.com/lavary/crunz/tree/3.2)?

**Comment by bashgeek** [comment]
> Could you add Symfony 6 checks to strategy matrix in `.github/workflows/code_checks.yaml` and change target branch to `3.2` (https://github.com/lavary/crunz/tree/3.2)?

Done!

**Comment by PabloKowalczyk** [comment]
For some reason Windows build failed and could rebase your branch on `3.2`?

**Comment by bashgeek** [comment]
> For some reason Windows build failed and could rebase your branch on `3.2`?

Seems to be an (newly introduced?) issue with the `shivammathur/setup-php@v2` runtime:
https://github.com/lavary/crunz/runs/4453789755?check_suite_focus=true#step:3:12

Had nothing to do with the changes made by me (didn't touch that part), it ran through fine in my workflow for the last commit (which is identical):
https://github.com/bashgeek/crunz/runs/4451594357?check_suite_focus=true

**Comment by PabloKowalczyk** [comment]
Sorry for that, but you started your branch on `master` and you have commit https://github.com/lavary/crunz/pull/390/commits/ab7c590a0c7403043803bde733a9d281eecce19f which shouldn't be there, also i plan to remove `master` branch. This is why there are changelog and readme changes. Could you remove mentioned commit?

You are right, looks like Windows CI fails are not related to your changes.

**Comment by bashgeek** [comment]
@PabloKowalczyk done!

**Comment by PabloKowalczyk** [comment]
Thank you @bashgeek

**Pull request merged**
