### PR TITLE
Additional autoloader possible path

### PR DESCRIPTION
**Pull request by MarkLittlewood**
| Q             | A
| ------------- | ---
| Fixed tickets | #207

### CODE REVIEW

**Comment by PabloKowalczyk** [comment]
Could you use `1.11.x` as a base branch for your PR? Currently your base branch is `master` which has changes intended for upcoming `v2` release.

**Comment by MarkLittlewood** [comment]
It won't let me change it, so I will close this PR and open another

**Comment by MarkLittlewood** [comment]
Sorry if I am being dense Pablo,  This PR had 1.11 as base and master as the compare.
Any other combination I try gives me no commits and leaves me unable to create a PR

**Comment by PabloKowalczyk** [comment]
Could you rebase your branch to `1.11.x` locally, then commit your changes, then try `git push --force`?
If you push new branches to your fork of Crunz, you cna change then by editing this PR.

**Comment by MarkLittlewood** [comment]
Will do, it will be tomorrow morning though.

Best Regards

Mark

**Comment by MarkLittlewood** [comment]
Sorry Pablo, but I get "Authentication failed" when I try to push

**Pull request closed without merging**
