### PR TITLE
Allow monolog 2.0 for compatibility with Laravel 7

### PR DESCRIPTION
**Pull request by jasonmccreary**

### CODE REVIEW

**Comment by jasonmccreary** [comment]
There are a handful of [breaking changes in 2.0](https://github.com/Seldaek/monolog/blob/2.0.0/UPGRADE.md) and the minimum requirement of PHP 7.2.

This is likely the cause of the build failures. Let me know how I can help.

**Comment by PabloKowalczyk** [comment]
Hello, please look at https://github.com/lavary/crunz/issues/259 - this is a preferred way to provide support for Monolog 2 and, as a bonus, all PSR-3 loggers.

**Comment by jasonmccreary** [comment]
I will. However, I still doubt this package can not be used with a Laravel 7 framework application due to the lower dependency.

**Comment by PabloKowalczyk** [comment]
Idea is that after #259 Crunz will no longer depends on `monolog/monolog`, only on `psr/log`, so nothing will block new Laravel, am i right?

**Comment by jasonmccreary** [comment]
Gotcha. Thanks for clarifying. I'll close this.

**Pull request closed without merging**
