### PR TITLE
1.x

### PR DESCRIPTION
**Pull request by mindcreations**
Fix for lavary/crunz#41 on branch 1.x with requested test

### CODE REVIEW

**Comment by mindcreations** [comment]
I see that with PHP v7.2 tests are not passing... it seems not a problem related with PHP version or the code itself... any ideas?

**Comment by PabloKowalczyk** [comment]
Coding style issues, run `composer crunz:cs-fix` in the project root.

**Comment by mindcreations** [comment]
It seems that CI exceeded 10 minutes, maybe you have to extend the timeout value.

**Comment by PabloKowalczyk** [comment]
Seems to be issues related to Travis itself, not the code. Thanks @mindcreations for PR.

**Pull request merged**
