### PR TITLE
Log to specific event log file

### PR DESCRIPTION
**Pull request by drjayvee**
| Q             | A
| ------------- | ---
| Fixed tickets | #309 #346

### CODE REVIEW

**Comment by PabloKowalczyk** [comment]
Hello @drjayvee, thanks for your PR!
Looks like CI is not happy, I saw you just added new code over `2.3.x` branch, but you should use https://github.com/lavary/crunz/pull/346 as a base branch, then add your code and finally push it here (feel free to use force push, it's your fork anyway).
Sorry for that bureaucracy, but it is needed, hope you know it :)

**Comment by drjayvee** [comment]
Whoops, my previous branch actually didn't have @rrushton's changes at all. Must have happened while cherry-picking.

I now merged https://github.com/alisqi/crunz/commit/f07569e55f51c74444efdefa31e2a7300f5b9fd1 into `2.3.x`.

**Comment by PabloKowalczyk** [comment]
Thanks, now better :) CI seems to be unhappy, one test fails and CS fixer reports some issues.

**Comment by drjayvee** [comment]
Regarding the PHPUnit test:
```
There was 1 error:

1) Crunz\Tests\EndToEnd\LoggerTest::test_event_logging_override
Error: Call to undefined method Crunz\Tests\EndToEnd\LoggerTest::assertFileDoesNotExist()

/home/runner/work/crunz/crunz/tests/EndToEnd/LoggerTest.php:60
/home/runner/work/crunz/crunz/vendor/phpunit/phpunit/phpunit:61
```
This works for me with the PHPUnit installed through composer.

Is this something I need to fix? Using `assertTrue(is_file())`?

**Comment by PabloKowalczyk** [comment]
Method `assertFileDoesNotExist` should be available in PHPUnit, what is installed version of PHPUnit?

**Comment by drjayvee** [comment]
For me:
```
../vendor/bin/phpunit --version
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.
```

But the `Code_Checks` uses `PHPUnit 8.5.15`, which does fit `composer.json`.

**Comment by PabloKowalczyk** [comment]
You are right, PHPUnit `8.5` is required on PHP `7.2` and it is also installed on "prefers lowest" jobs.
Could you add `assertFileDoesNotExist` method to `\Crunz\Tests\TestCase\PolyfillAssertTrait` with `file_exists` check? With this code will be forward compatible.

**Comment by drjayvee** [comment]
Hi @PabloKowalczyk, sorry for taking so long again, but here you go!

**Comment by PabloKowalczyk** [comment]
Almost there :) One case failed in CI, it's related to CSFixer.

**Comment by PabloKowalczyk** [comment]
Sorry, now PHPStan reports some issues.

**Comment by drjayvee** [comment]
There we go. I should have probably tried running those tools locally as best as I can.

**Comment by PabloKowalczyk** [comment]
There is `composer crunz:cs-fix` and `composer phpstan:check` shortcuts for this, but make sure you have Symfony at v4.4 (same as in CI).
CI still fails, now CSFixer issue.

**Comment by drjayvee** [comment]
Hm,
```
$ composer crunz:cs-fix
> @php vendor/bin/php-cs-fixer fix --diff -v --ansi
Could not open input file: vendor/bin/php-cs-fixer
Script @php vendor/bin/php-cs-fixer fix --diff -v --ansi handling the crunz:cs-fix event returned with error code 1
```

Should `php-cs-fixer` be `composer require`d perhaps?

**Comment by PabloKowalczyk** [comment]
> Should php-cs-fixer be composer required perhaps?

It is, but only in `require-dev` section.

PR merged, thanks @drjayvee.

**Comment by drjayvee** [comment]
> It is, but only in `require-dev` section.

I don't see it!

> PR merged, thanks @drjayvee.

Thanks a lot for the fresh release. Also, thanks to @rrushton for the actual code!

**Comment by rrushton** [comment]
Thanks @drjayvee for seeing this through!

**Pull request merged**
